logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: ERROR

spring:
  application:
    name: mashupmedia
  h2:
    console:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF
      suffix: .jsp
    servlet:
      path: /

server:
  servlet:
    context-path: /mashupmedia