spring:
  mail:
    host: mail.mashupmedia.org
    port: 465
    username: andy@mashupmedia.org
    password: MikeDonkey8Twig2Sewer
    properties:
      mail:
        smtp:
          auth: true
     