logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: ERROR

spring:
  application:
    name: mashupmedia
  mvc:
    async:
      request-timeout: 360000
  jpa:
    hibernate:
      ddl-auto: validate 
      # ddl-auto: update

    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        # cache:
        #   use_query_cache: true
        #   use_second_level_cache: true
          # region:
          #   factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        query:
          substitutions: "true '1', false '0'"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    rest:
      default-media-type: application/json
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
  jackson:      
    default-property-inclusion: non-absent    
  liquibase:
    change-log: classpath:config/liquibase/master.xml

server:
  port: 8080  
  servlet:
    context-path: /mashupmedia
    host: https://www.mashupmedia.org
    encoding:
      charset: utf-8

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    operations-sorter: method
    path: /swagger/swagger-ui.html

mashupmedia:
  storage: file