logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: ERROR

spring:
  application:
    name: mashupmedia
  mvc:
    async:
      request-timeout: 360000
      
    

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    rest:
      default-media-type: application/json
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs


  jackson:      
    default-property-inclusion: non-absent

server:
  port: 8080
  
  servlet:
    context-path: /mashupmedia
    host: https://www.mashupmedia.org
    encoding:
      charset: utf-8

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    operations-sorter: method
    path: /swagger/swagger-ui.html